/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package walletapiv2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The request model sent by the client for adding new bank accounts to the
 * payment platform.
 */
public class BankAccountRequestModel {
    /**
     * The bank account number.
     */
    @JsonProperty(value = "accountNumber", required = true)
    private String accountNumber;

    /**
     * The routing number of the bank where the bank account was opened.
     */
    @JsonProperty(value = "routingNumber", required = true)
    private String routingNumber;

    /**
     * The name of the individual or entity that is autorized to make
     * transactions for the bank account.
     */
    @JsonProperty(value = "accountHolderName", required = true)
    private String accountHolderName;

    /**
     * The mailing address for the account holder.
     */
    @JsonProperty(value = "accountHolderAddress", required = true)
    private Address accountHolderAddress;

    /**
     * The bank account type. Possible values include: 'Unknown', 'Checking',
     * 'Savings'.
     */
    @JsonProperty(value = "type", required = true)
    private String type;

    /**
     * The client application provided reference ID for the bank account.
     */
    @JsonProperty(value = "referenceId")
    private String referenceId;

    /**
     * The aribtrary nickname of the account, used as a way to identify the
     * account.
     */
    @JsonProperty(value = "nickname")
    private String nickname;

    /**
     * The email address for the account holder.
     */
    @JsonProperty(value = "email", required = true)
    private String email;

    /**
     * The url that the client will be redirected to after the bank account has
     * been created.
     */
    @JsonProperty(value = "redirectUrl")
    private String redirectUrl;

    /**
     * Get the bank account number.
     *
     * @return the accountNumber value
     */
    public String accountNumber() {
        return this.accountNumber;
    }

    /**
     * Set the bank account number.
     *
     * @param accountNumber the accountNumber value to set
     * @return the BankAccountRequestModel object itself.
     */
    public BankAccountRequestModel withAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }

    /**
     * Get the routing number of the bank where the bank account was opened.
     *
     * @return the routingNumber value
     */
    public String routingNumber() {
        return this.routingNumber;
    }

    /**
     * Set the routing number of the bank where the bank account was opened.
     *
     * @param routingNumber the routingNumber value to set
     * @return the BankAccountRequestModel object itself.
     */
    public BankAccountRequestModel withRoutingNumber(String routingNumber) {
        this.routingNumber = routingNumber;
        return this;
    }

    /**
     * Get the name of the individual or entity that is autorized to make transactions for the bank account.
     *
     * @return the accountHolderName value
     */
    public String accountHolderName() {
        return this.accountHolderName;
    }

    /**
     * Set the name of the individual or entity that is autorized to make transactions for the bank account.
     *
     * @param accountHolderName the accountHolderName value to set
     * @return the BankAccountRequestModel object itself.
     */
    public BankAccountRequestModel withAccountHolderName(String accountHolderName) {
        this.accountHolderName = accountHolderName;
        return this;
    }

    /**
     * Get the mailing address for the account holder.
     *
     * @return the accountHolderAddress value
     */
    public Address accountHolderAddress() {
        return this.accountHolderAddress;
    }

    /**
     * Set the mailing address for the account holder.
     *
     * @param accountHolderAddress the accountHolderAddress value to set
     * @return the BankAccountRequestModel object itself.
     */
    public BankAccountRequestModel withAccountHolderAddress(Address accountHolderAddress) {
        this.accountHolderAddress = accountHolderAddress;
        return this;
    }

    /**
     * Get the bank account type. Possible values include: 'Unknown', 'Checking', 'Savings'.
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the bank account type. Possible values include: 'Unknown', 'Checking', 'Savings'.
     *
     * @param type the type value to set
     * @return the BankAccountRequestModel object itself.
     */
    public BankAccountRequestModel withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the client application provided reference ID for the bank account.
     *
     * @return the referenceId value
     */
    public String referenceId() {
        return this.referenceId;
    }

    /**
     * Set the client application provided reference ID for the bank account.
     *
     * @param referenceId the referenceId value to set
     * @return the BankAccountRequestModel object itself.
     */
    public BankAccountRequestModel withReferenceId(String referenceId) {
        this.referenceId = referenceId;
        return this;
    }

    /**
     * Get the aribtrary nickname of the account, used as a way to identify the account.
     *
     * @return the nickname value
     */
    public String nickname() {
        return this.nickname;
    }

    /**
     * Set the aribtrary nickname of the account, used as a way to identify the account.
     *
     * @param nickname the nickname value to set
     * @return the BankAccountRequestModel object itself.
     */
    public BankAccountRequestModel withNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    /**
     * Get the email address for the account holder.
     *
     * @return the email value
     */
    public String email() {
        return this.email;
    }

    /**
     * Set the email address for the account holder.
     *
     * @param email the email value to set
     * @return the BankAccountRequestModel object itself.
     */
    public BankAccountRequestModel withEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get the url that the client will be redirected to after the bank account has been created.
     *
     * @return the redirectUrl value
     */
    public String redirectUrl() {
        return this.redirectUrl;
    }

    /**
     * Set the url that the client will be redirected to after the bank account has been created.
     *
     * @param redirectUrl the redirectUrl value to set
     * @return the BankAccountRequestModel object itself.
     */
    public BankAccountRequestModel withRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
        return this;
    }

}
