/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.wallet.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines a BIN (bank identification number).
 */
public class Bin {
    /**
     * Gets the bin.
     */
    @JsonProperty(value = "bin")
    private String bin;

    /**
     * Gets or sets the brand. Possible values include: 'Unknown', 'Visa',
     * 'MasterCard', 'Amex', 'Discover'.
     */
    @JsonProperty(value = "brand", access = JsonProperty.Access.WRITE_ONLY)
    private String brand;

    /**
     * Gets or sets a value indicating whether this instance is debit.
     */
    @JsonProperty(value = "isDebitCard")
    private Boolean isDebitCard;

    /**
     * Gets or sets a value indicating whether this instance is check card.
     */
    @JsonProperty(value = "isCheckCard")
    private Boolean isCheckCard;

    /**
     * Gets or sets a value indicating whether this instance is gift card.
     */
    @JsonProperty(value = "isGiftCard")
    private Boolean isGiftCard;

    /**
     * Gets or sets a value indicating whether this instance is corporate card.
     */
    @JsonProperty(value = "isCorporateCard")
    private Boolean isCorporateCard;

    /**
     * Gets or sets a value indicating whether this instance is fleet card.
     */
    @JsonProperty(value = "isFleetCard")
    private Boolean isFleetCard;

    /**
     * Gets or sets a value indicating whether this instance is prepaid card.
     */
    @JsonProperty(value = "isPrepaidCard")
    private Boolean isPrepaidCard;

    /**
     * Get the bin value.
     *
     * @return the bin value
     */
    public String bin() {
        return this.bin;
    }

    /**
     * Set the bin value.
     *
     * @param bin the bin value to set
     * @return the Bin object itself.
     */
    public Bin withBin(String bin) {
        this.bin = bin;
        return this;
    }

    /**
     * Get the brand value.
     *
     * @return the brand value
     */
    public String brand() {
        return this.brand;
    }

    /**
     * Get the isDebitCard value.
     *
     * @return the isDebitCard value
     */
    public Boolean isDebitCard() {
        return this.isDebitCard;
    }

    /**
     * Set the isDebitCard value.
     *
     * @param isDebitCard the isDebitCard value to set
     * @return the Bin object itself.
     */
    public Bin withIsDebitCard(Boolean isDebitCard) {
        this.isDebitCard = isDebitCard;
        return this;
    }

    /**
     * Get the isCheckCard value.
     *
     * @return the isCheckCard value
     */
    public Boolean isCheckCard() {
        return this.isCheckCard;
    }

    /**
     * Set the isCheckCard value.
     *
     * @param isCheckCard the isCheckCard value to set
     * @return the Bin object itself.
     */
    public Bin withIsCheckCard(Boolean isCheckCard) {
        this.isCheckCard = isCheckCard;
        return this;
    }

    /**
     * Get the isGiftCard value.
     *
     * @return the isGiftCard value
     */
    public Boolean isGiftCard() {
        return this.isGiftCard;
    }

    /**
     * Set the isGiftCard value.
     *
     * @param isGiftCard the isGiftCard value to set
     * @return the Bin object itself.
     */
    public Bin withIsGiftCard(Boolean isGiftCard) {
        this.isGiftCard = isGiftCard;
        return this;
    }

    /**
     * Get the isCorporateCard value.
     *
     * @return the isCorporateCard value
     */
    public Boolean isCorporateCard() {
        return this.isCorporateCard;
    }

    /**
     * Set the isCorporateCard value.
     *
     * @param isCorporateCard the isCorporateCard value to set
     * @return the Bin object itself.
     */
    public Bin withIsCorporateCard(Boolean isCorporateCard) {
        this.isCorporateCard = isCorporateCard;
        return this;
    }

    /**
     * Get the isFleetCard value.
     *
     * @return the isFleetCard value
     */
    public Boolean isFleetCard() {
        return this.isFleetCard;
    }

    /**
     * Set the isFleetCard value.
     *
     * @param isFleetCard the isFleetCard value to set
     * @return the Bin object itself.
     */
    public Bin withIsFleetCard(Boolean isFleetCard) {
        this.isFleetCard = isFleetCard;
        return this;
    }

    /**
     * Get the isPrepaidCard value.
     *
     * @return the isPrepaidCard value
     */
    public Boolean isPrepaidCard() {
        return this.isPrepaidCard;
    }

    /**
     * Set the isPrepaidCard value.
     *
     * @param isPrepaidCard the isPrepaidCard value to set
     * @return the Bin object itself.
     */
    public Bin withIsPrepaidCard(Boolean isPrepaidCard) {
        this.isPrepaidCard = isPrepaidCard;
        return this;
    }

}
