/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package walletapiv2.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The model sent to the client as a part of the payment model.
 * Provides details on the payment result.
 */
public class PaymentResultModel {
    /**
     * The current status of the payment. Possible values include: 'Unknown',
     * 'New', 'Authorized', 'Captured', 'Expired', 'Declined', 'Failed',
     * 'Cancelled', 'Charge Back', 'Refunded', 'Partially Refunded'.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * The payment result code.
     */
    @JsonProperty(value = "code")
    private String code;

    /**
     * The payment result message.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * The unique ID of the provider account that was used to make this
     * payment.
     */
    @JsonProperty(value = "providerAccountId")
    private String providerAccountId;

    /**
     * Tthe merchant transaction identifier.
     */
    @JsonProperty(value = "merchantTransactionId")
    private String merchantTransactionId;

    /**
     * The merchant transaction fee.
     */
    @JsonProperty(value = "merchantTransactionFee")
    private Double merchantTransactionFee;

    /**
     * Get the current status of the payment. Possible values include: 'Unknown', 'New', 'Authorized', 'Captured', 'Expired', 'Declined', 'Failed', 'Cancelled', 'Charge Back', 'Refunded', 'Partially Refunded'.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set the current status of the payment. Possible values include: 'Unknown', 'New', 'Authorized', 'Captured', 'Expired', 'Declined', 'Failed', 'Cancelled', 'Charge Back', 'Refunded', 'Partially Refunded'.
     *
     * @param status the status value to set
     * @return the PaymentResultModel object itself.
     */
    public PaymentResultModel withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get the payment result code.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the payment result code.
     *
     * @param code the code value to set
     * @return the PaymentResultModel object itself.
     */
    public PaymentResultModel withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get the payment result message.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the payment result message.
     *
     * @param message the message value to set
     * @return the PaymentResultModel object itself.
     */
    public PaymentResultModel withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the unique ID of the provider account that was used to make this payment.
     *
     * @return the providerAccountId value
     */
    public String providerAccountId() {
        return this.providerAccountId;
    }

    /**
     * Set the unique ID of the provider account that was used to make this payment.
     *
     * @param providerAccountId the providerAccountId value to set
     * @return the PaymentResultModel object itself.
     */
    public PaymentResultModel withProviderAccountId(String providerAccountId) {
        this.providerAccountId = providerAccountId;
        return this;
    }

    /**
     * Get tthe merchant transaction identifier.
     *
     * @return the merchantTransactionId value
     */
    public String merchantTransactionId() {
        return this.merchantTransactionId;
    }

    /**
     * Set tthe merchant transaction identifier.
     *
     * @param merchantTransactionId the merchantTransactionId value to set
     * @return the PaymentResultModel object itself.
     */
    public PaymentResultModel withMerchantTransactionId(String merchantTransactionId) {
        this.merchantTransactionId = merchantTransactionId;
        return this;
    }

    /**
     * Get the merchant transaction fee.
     *
     * @return the merchantTransactionFee value
     */
    public Double merchantTransactionFee() {
        return this.merchantTransactionFee;
    }

    /**
     * Set the merchant transaction fee.
     *
     * @param merchantTransactionFee the merchantTransactionFee value to set
     * @return the PaymentResultModel object itself.
     */
    public PaymentResultModel withMerchantTransactionFee(Double merchantTransactionFee) {
        this.merchantTransactionFee = merchantTransactionFee;
        return this;
    }

}
