/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package walletapiv2.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The model sent to the client as a part of the payment model.
 * Provides details on the refund result.
 */
public class RefundResultModel {
    /**
     * The current status of the refund. Possible values include: 'Unknown',
     * 'New', 'Authorized', 'Captured', 'Expired', 'Declined', 'Failed',
     * 'Cancelled', 'Charge Back', 'Refunded', 'Partially Refunded'.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * The refund result code.
     */
    @JsonProperty(value = "code")
    private String code;

    /**
     * The refund result message.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * The Merchant Transaction ID number for the payment that is being
     * refunded.
     */
    @JsonProperty(value = "merchantTransactionId")
    private String merchantTransactionId;

    /**
     * The unique ID of the provider account that was used to make this refund.
     */
    @JsonProperty(value = "providerAccountId")
    private String providerAccountId;

    /**
     * The amount to be refunded.  If an amount less than the original payment
     * amount is
     * specified, a partial refund will be processed.  If no amount is
     * specified, a full refund
     * will be processed.
     */
    @JsonProperty(value = "amount")
    private Double amount;

    /**
     * The reason for issuing the refund.
     */
    @JsonProperty(value = "reason")
    private String reason;

    /**
     * The timestamp indicating when the refund was created.
     */
    @JsonProperty(value = "createdDate")
    private DateTime createdDate;

    /**
     * Get the current status of the refund. Possible values include: 'Unknown', 'New', 'Authorized', 'Captured', 'Expired', 'Declined', 'Failed', 'Cancelled', 'Charge Back', 'Refunded', 'Partially Refunded'.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set the current status of the refund. Possible values include: 'Unknown', 'New', 'Authorized', 'Captured', 'Expired', 'Declined', 'Failed', 'Cancelled', 'Charge Back', 'Refunded', 'Partially Refunded'.
     *
     * @param status the status value to set
     * @return the RefundResultModel object itself.
     */
    public RefundResultModel withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get the refund result code.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the refund result code.
     *
     * @param code the code value to set
     * @return the RefundResultModel object itself.
     */
    public RefundResultModel withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get the refund result message.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the refund result message.
     *
     * @param message the message value to set
     * @return the RefundResultModel object itself.
     */
    public RefundResultModel withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the Merchant Transaction ID number for the payment that is being refunded.
     *
     * @return the merchantTransactionId value
     */
    public String merchantTransactionId() {
        return this.merchantTransactionId;
    }

    /**
     * Set the Merchant Transaction ID number for the payment that is being refunded.
     *
     * @param merchantTransactionId the merchantTransactionId value to set
     * @return the RefundResultModel object itself.
     */
    public RefundResultModel withMerchantTransactionId(String merchantTransactionId) {
        this.merchantTransactionId = merchantTransactionId;
        return this;
    }

    /**
     * Get the unique ID of the provider account that was used to make this refund.
     *
     * @return the providerAccountId value
     */
    public String providerAccountId() {
        return this.providerAccountId;
    }

    /**
     * Set the unique ID of the provider account that was used to make this refund.
     *
     * @param providerAccountId the providerAccountId value to set
     * @return the RefundResultModel object itself.
     */
    public RefundResultModel withProviderAccountId(String providerAccountId) {
        this.providerAccountId = providerAccountId;
        return this;
    }

    /**
     * Get the amount to be refunded.  If an amount less than the original payment amount is
     specified, a partial refund will be processed.  If no amount is specified, a full refund
     will be processed.
     *
     * @return the amount value
     */
    public Double amount() {
        return this.amount;
    }

    /**
     * Set the amount to be refunded.  If an amount less than the original payment amount is
     specified, a partial refund will be processed.  If no amount is specified, a full refund
     will be processed.
     *
     * @param amount the amount value to set
     * @return the RefundResultModel object itself.
     */
    public RefundResultModel withAmount(Double amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Get the reason for issuing the refund.
     *
     * @return the reason value
     */
    public String reason() {
        return this.reason;
    }

    /**
     * Set the reason for issuing the refund.
     *
     * @param reason the reason value to set
     * @return the RefundResultModel object itself.
     */
    public RefundResultModel withReason(String reason) {
        this.reason = reason;
        return this;
    }

    /**
     * Get the timestamp indicating when the refund was created.
     *
     * @return the createdDate value
     */
    public DateTime createdDate() {
        return this.createdDate;
    }

    /**
     * Set the timestamp indicating when the refund was created.
     *
     * @param createdDate the createdDate value to set
     * @return the RefundResultModel object itself.
     */
    public RefundResultModel withCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

}
