/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package walletapiv2.models;

import java.util.Map;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The request model sent by the client for adding new subscription to the
 * payment platform.
 */
public class SubscriptionRequestModel {
    /**
     * The name of payment subscription.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The description of payment subscription.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * The properties of the payment subscription.
     */
    @JsonProperty(value = "properties")
    private Map<String, String> properties;

    /**
     * The process day of the payment subscription.
     */
    @JsonProperty(value = "runDay", required = true)
    private int runDay;

    /**
     * The state that payment subscription is in. Possible values include:
     * 'Active', 'Inactive', 'Expired'.
     */
    @JsonProperty(value = "state", required = true)
    private String state;

    /**
     * The payment type of the payment subscription. Possible values include:
     * 'Unknown', 'Credit Card', 'ACH'.
     */
    @JsonProperty(value = "paymentType", required = true)
    private String paymentType;

    /**
     * The payment token of the payment subscription.
     */
    @JsonProperty(value = "paymentToken", required = true)
    private String paymentToken;

    /**
     * The amount type of the payment subscription. Possible values include:
     * 'Fixed', 'Dynamic'.
     */
    @JsonProperty(value = "amountType", required = true)
    private String amountType;

    /**
     * The amount of money to be charged by the payment subscription.
     */
    @JsonProperty(value = "amount")
    private Double amount;

    /**
     * The url of web api to use to retrieve the amount to be charged by the
     * payment subscription.
     */
    @JsonProperty(value = "amountWebServiceURL")
    private String amountWebServiceURL;

    /**
     * The url of a web api to use to post back notifications each time payment
     * subscription is processed.
     */
    @JsonProperty(value = "callbackWebServiceURL")
    private String callbackWebServiceURL;

    /**
     * The date indicating when the payment subscription should be stopped.
     */
    @JsonProperty(value = "endDate")
    private DateTime endDate;

    /**
     * The client application provided reference ID for the credit card.
     */
    @JsonProperty(value = "referenceId")
    private String referenceId;

    /**
     * Get the name of payment subscription.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name of payment subscription.
     *
     * @param name the name value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the description of payment subscription.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description of payment subscription.
     *
     * @param description the description value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the properties of the payment subscription.
     *
     * @return the properties value
     */
    public Map<String, String> properties() {
        return this.properties;
    }

    /**
     * Set the properties of the payment subscription.
     *
     * @param properties the properties value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withProperties(Map<String, String> properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get the process day of the payment subscription.
     *
     * @return the runDay value
     */
    public int runDay() {
        return this.runDay;
    }

    /**
     * Set the process day of the payment subscription.
     *
     * @param runDay the runDay value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withRunDay(int runDay) {
        this.runDay = runDay;
        return this;
    }

    /**
     * Get the state that payment subscription is in. Possible values include: 'Active', 'Inactive', 'Expired'.
     *
     * @return the state value
     */
    public String state() {
        return this.state;
    }

    /**
     * Set the state that payment subscription is in. Possible values include: 'Active', 'Inactive', 'Expired'.
     *
     * @param state the state value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Get the payment type of the payment subscription. Possible values include: 'Unknown', 'Credit Card', 'ACH'.
     *
     * @return the paymentType value
     */
    public String paymentType() {
        return this.paymentType;
    }

    /**
     * Set the payment type of the payment subscription. Possible values include: 'Unknown', 'Credit Card', 'ACH'.
     *
     * @param paymentType the paymentType value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withPaymentType(String paymentType) {
        this.paymentType = paymentType;
        return this;
    }

    /**
     * Get the payment token of the payment subscription.
     *
     * @return the paymentToken value
     */
    public String paymentToken() {
        return this.paymentToken;
    }

    /**
     * Set the payment token of the payment subscription.
     *
     * @param paymentToken the paymentToken value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withPaymentToken(String paymentToken) {
        this.paymentToken = paymentToken;
        return this;
    }

    /**
     * Get the amount type of the payment subscription. Possible values include: 'Fixed', 'Dynamic'.
     *
     * @return the amountType value
     */
    public String amountType() {
        return this.amountType;
    }

    /**
     * Set the amount type of the payment subscription. Possible values include: 'Fixed', 'Dynamic'.
     *
     * @param amountType the amountType value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withAmountType(String amountType) {
        this.amountType = amountType;
        return this;
    }

    /**
     * Get the amount of money to be charged by the payment subscription.
     *
     * @return the amount value
     */
    public Double amount() {
        return this.amount;
    }

    /**
     * Set the amount of money to be charged by the payment subscription.
     *
     * @param amount the amount value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withAmount(Double amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Get the url of web api to use to retrieve the amount to be charged by the payment subscription.
     *
     * @return the amountWebServiceURL value
     */
    public String amountWebServiceURL() {
        return this.amountWebServiceURL;
    }

    /**
     * Set the url of web api to use to retrieve the amount to be charged by the payment subscription.
     *
     * @param amountWebServiceURL the amountWebServiceURL value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withAmountWebServiceURL(String amountWebServiceURL) {
        this.amountWebServiceURL = amountWebServiceURL;
        return this;
    }

    /**
     * Get the url of a web api to use to post back notifications each time payment subscription is processed.
     *
     * @return the callbackWebServiceURL value
     */
    public String callbackWebServiceURL() {
        return this.callbackWebServiceURL;
    }

    /**
     * Set the url of a web api to use to post back notifications each time payment subscription is processed.
     *
     * @param callbackWebServiceURL the callbackWebServiceURL value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withCallbackWebServiceURL(String callbackWebServiceURL) {
        this.callbackWebServiceURL = callbackWebServiceURL;
        return this;
    }

    /**
     * Get the date indicating when the payment subscription should be stopped.
     *
     * @return the endDate value
     */
    public DateTime endDate() {
        return this.endDate;
    }

    /**
     * Set the date indicating when the payment subscription should be stopped.
     *
     * @param endDate the endDate value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withEndDate(DateTime endDate) {
        this.endDate = endDate;
        return this;
    }

    /**
     * Get the client application provided reference ID for the credit card.
     *
     * @return the referenceId value
     */
    public String referenceId() {
        return this.referenceId;
    }

    /**
     * Set the client application provided reference ID for the credit card.
     *
     * @param referenceId the referenceId value to set
     * @return the SubscriptionRequestModel object itself.
     */
    public SubscriptionRequestModel withReferenceId(String referenceId) {
        this.referenceId = referenceId;
        return this;
    }

}
