/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package softheon.wallet.api.client.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The request model sent by the client for updating bank accounts in the
 * payment platform.
 */
public class UpdateBankAccountModel {
    /**
     * The payment token for the bank account.
     */
    @JsonProperty(value = "token")
    private String token;

    /**
     * The aribtrary nickname of the account, used as a way to identify the
     * account.
     */
    @JsonProperty(value = "nickname")
    private String nickname;

    /**
     * The name of the individual or entity that is autorized to make
     * transactions for the bank account.
     */
    @JsonProperty(value = "accountHolderName", required = true)
    private String accountHolderName;

    /**
     * The mailing address for the account holder.
     */
    @JsonProperty(value = "accountHolderAddress", required = true)
    private Address accountHolderAddress;

    /**
     * The email address for the account holder.
     */
    @JsonProperty(value = "email", required = true)
    private String email;

    /**
     * Get the token value.
     *
     * @return the token value
     */
    public String token() {
        return this.token;
    }

    /**
     * Set the token value.
     *
     * @param token the token value to set
     * @return the UpdateBankAccountModel object itself.
     */
    public UpdateBankAccountModel withToken(String token) {
        this.token = token;
        return this;
    }

    /**
     * Get the nickname value.
     *
     * @return the nickname value
     */
    public String nickname() {
        return this.nickname;
    }

    /**
     * Set the nickname value.
     *
     * @param nickname the nickname value to set
     * @return the UpdateBankAccountModel object itself.
     */
    public UpdateBankAccountModel withNickname(String nickname) {
        this.nickname = nickname;
        return this;
    }

    /**
     * Get the accountHolderName value.
     *
     * @return the accountHolderName value
     */
    public String accountHolderName() {
        return this.accountHolderName;
    }

    /**
     * Set the accountHolderName value.
     *
     * @param accountHolderName the accountHolderName value to set
     * @return the UpdateBankAccountModel object itself.
     */
    public UpdateBankAccountModel withAccountHolderName(String accountHolderName) {
        this.accountHolderName = accountHolderName;
        return this;
    }

    /**
     * Get the accountHolderAddress value.
     *
     * @return the accountHolderAddress value
     */
    public Address accountHolderAddress() {
        return this.accountHolderAddress;
    }

    /**
     * Set the accountHolderAddress value.
     *
     * @param accountHolderAddress the accountHolderAddress value to set
     * @return the UpdateBankAccountModel object itself.
     */
    public UpdateBankAccountModel withAccountHolderAddress(Address accountHolderAddress) {
        this.accountHolderAddress = accountHolderAddress;
        return this;
    }

    /**
     * Get the email value.
     *
     * @return the email value
     */
    public String email() {
        return this.email;
    }

    /**
     * Set the email value.
     *
     * @param email the email value to set
     * @return the UpdateBankAccountModel object itself.
     */
    public UpdateBankAccountModel withEmail(String email) {
        this.email = email;
        return this;
    }

}
