// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Wallet.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The response model that is returned to the client when a new bank
    /// account is added
    /// to the platform
    /// </summary>
    public partial class BankAccountResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the BankAccountResponseModel class.
        /// </summary>
        public BankAccountResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BankAccountResponseModel class.
        /// </summary>
        /// <param name="token">The payment token for the bank account.</param>
        /// <param name="bankAccountState">The state that the bank acocunt is
        /// in. Possible values include: 'Unknown', 'New', 'Pending',
        /// 'Authorized', 'Disabled'</param>
        /// <param name="redirectUrl">The url that the client will be
        /// redirected to after the bank account has been created.</param>
        public BankAccountResponseModel(string token = default(string), string bankAccountState = default(string), string redirectUrl = default(string))
        {
            Token = token;
            BankAccountState = bankAccountState;
            RedirectUrl = redirectUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the payment token for the bank account.
        /// </summary>
        [JsonProperty(PropertyName = "token")]
        public string Token { get; set; }

        /// <summary>
        /// Gets or sets the state that the bank acocunt is in. Possible values
        /// include: 'Unknown', 'New', 'Pending', 'Authorized', 'Disabled'
        /// </summary>
        [JsonProperty(PropertyName = "bankAccountState")]
        public string BankAccountState { get; set; }

        /// <summary>
        /// Gets or sets the url that the client will be redirected to after
        /// the bank account has been created.
        /// </summary>
        [JsonProperty(PropertyName = "redirectUrl")]
        public string RedirectUrl { get; set; }

    }
}
