// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Wallet.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines a BIN (bank identification number)
    /// </summary>
    public partial class Bin
    {
        /// <summary>
        /// Initializes a new instance of the Bin class.
        /// </summary>
        public Bin()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Bin class.
        /// </summary>
        /// <param name="binProperty">Gets the bin.</param>
        /// <param name="brand">Gets or sets the brand. Possible values
        /// include: 'Unknown', 'Visa', 'MasterCard', 'Amex',
        /// 'Discover'</param>
        /// <param name="isDebitCard">Gets or sets a value indicating whether
        /// this instance is debit.</param>
        /// <param name="isCheckCard">Gets or sets a value indicating whether
        /// this instance is check card.</param>
        /// <param name="isGiftCard">Gets or sets a value indicating whether
        /// this instance is gift card.</param>
        /// <param name="isCorporateCard">Gets or sets a value indicating
        /// whether this instance is corporate card.</param>
        /// <param name="isFleetCard">Gets or sets a value indicating whether
        /// this instance is fleet card.</param>
        /// <param name="isPrepaidCard">Gets or sets a value indicating whether
        /// this instance is prepaid card.</param>
        public Bin(string binProperty = default(string), string brand = default(string), bool? isDebitCard = default(bool?), bool? isCheckCard = default(bool?), bool? isGiftCard = default(bool?), bool? isCorporateCard = default(bool?), bool? isFleetCard = default(bool?), bool? isPrepaidCard = default(bool?))
        {
            BinProperty = binProperty;
            Brand = brand;
            IsDebitCard = isDebitCard;
            IsCheckCard = isCheckCard;
            IsGiftCard = isGiftCard;
            IsCorporateCard = isCorporateCard;
            IsFleetCard = isFleetCard;
            IsPrepaidCard = isPrepaidCard;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the bin.
        /// </summary>
        [JsonProperty(PropertyName = "bin")]
        public string BinProperty { get; set; }

        /// <summary>
        /// Gets or sets the brand. Possible values include: 'Unknown', 'Visa',
        /// 'MasterCard', 'Amex', 'Discover'
        /// </summary>
        [JsonProperty(PropertyName = "brand")]
        public string Brand { get; private set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is debit.
        /// </summary>
        [JsonProperty(PropertyName = "isDebitCard")]
        public bool? IsDebitCard { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is check
        /// card.
        /// </summary>
        [JsonProperty(PropertyName = "isCheckCard")]
        public bool? IsCheckCard { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is gift card.
        /// </summary>
        [JsonProperty(PropertyName = "isGiftCard")]
        public bool? IsGiftCard { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is corporate
        /// card.
        /// </summary>
        [JsonProperty(PropertyName = "isCorporateCard")]
        public bool? IsCorporateCard { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is fleet
        /// card.
        /// </summary>
        [JsonProperty(PropertyName = "isFleetCard")]
        public bool? IsFleetCard { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is prepaid
        /// card.
        /// </summary>
        [JsonProperty(PropertyName = "isPrepaidCard")]
        public bool? IsPrepaidCard { get; set; }

    }
}
