// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Softheon.Wallet.Api.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The response model that is returned to the client when a new payment
    /// subscription is added to the platform.
    /// </summary>
    public partial class SubscriptionResponceModel
    {
        /// <summary>
        /// Initializes a new instance of the SubscriptionResponceModel class.
        /// </summary>
        public SubscriptionResponceModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubscriptionResponceModel class.
        /// </summary>
        /// <param name="referenceId">Gets or sets the reference id.</param>
        /// <param name="state">Gets or sets the subscription state. Possible
        /// values include: 'Active', 'Inactive', 'Expired'</param>
        public SubscriptionResponceModel(string referenceId = default(string), string state = default(string))
        {
            ReferenceId = referenceId;
            State = state;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the reference id.
        /// </summary>
        [JsonProperty(PropertyName = "referenceId")]
        public string ReferenceId { get; set; }

        /// <summary>
        /// Gets or sets the subscription state. Possible values include:
        /// 'Active', 'Inactive', 'Expired'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string State { get; set; }

    }
}
