/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


export const Address = {
  required: false,
  serializedName: 'Address',
  type: {
    name: 'Composite',
    className: 'Address',
    modelProperties: {
      address1: {
        required: true,
        serializedName: 'address1',
        type: {
          name: 'String'
        }
      },
      address2: {
        required: false,
        serializedName: 'address2',
        type: {
          name: 'String'
        }
      },
      city: {
        required: true,
        serializedName: 'city',
        type: {
          name: 'String'
        }
      },
      state: {
        required: true,
        serializedName: 'state',
        type: {
          name: 'String'
        }
      },
      zipCode: {
        required: true,
        serializedName: 'zipCode',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const BankAccountModel = {
  required: false,
  serializedName: 'BankAccountModel',
  type: {
    name: 'Composite',
    className: 'BankAccountModel',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      token: {
        required: false,
        serializedName: 'token',
        type: {
          name: 'String'
        }
      },
      accountNumber: {
        required: false,
        serializedName: 'accountNumber',
        constraints: {
          Pattern: '\d{4,17}$'
        },
        type: {
          name: 'String'
        }
      },
      routingNumber: {
        required: true,
        serializedName: 'routingNumber',
        constraints: {
          Pattern: '\d{9,9}$'
        },
        type: {
          name: 'String'
        }
      },
      type: {
        required: true,
        serializedName: 'type',
        type: {
          name: 'String'
        }
      },
      state: {
        required: true,
        serializedName: 'state',
        type: {
          name: 'String'
        }
      },
      nickname: {
        required: false,
        serializedName: 'nickname',
        type: {
          name: 'String'
        }
      },
      accountHolderName: {
        required: true,
        serializedName: 'accountHolderName',
        type: {
          name: 'String'
        }
      },
      accountHolderAddress: {
        required: true,
        serializedName: 'accountHolderAddress',
        type: {
          name: 'Composite',
          className: 'Address'
        }
      },
      email: {
        required: true,
        serializedName: 'email',
        type: {
          name: 'String'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      createdTime: {
        required: false,
        serializedName: 'createdTime',
        type: {
          name: 'DateTime'
        }
      },
      modifiedTime: {
        required: false,
        serializedName: 'modifiedTime',
        type: {
          name: 'DateTime'
        }
      }
    }
  }
};

export const BankAccountRequestModel = {
  required: false,
  serializedName: 'BankAccountRequestModel',
  type: {
    name: 'Composite',
    className: 'BankAccountRequestModel',
    modelProperties: {
      accountNumber: {
        required: true,
        serializedName: 'accountNumber',
        constraints: {
          Pattern: '\d{4,17}$'
        },
        type: {
          name: 'String'
        }
      },
      routingNumber: {
        required: true,
        serializedName: 'routingNumber',
        constraints: {
          Pattern: '\d{9,9}$'
        },
        type: {
          name: 'String'
        }
      },
      accountHolderName: {
        required: true,
        serializedName: 'accountHolderName',
        type: {
          name: 'String'
        }
      },
      accountHolderAddress: {
        required: true,
        serializedName: 'accountHolderAddress',
        type: {
          name: 'Composite',
          className: 'Address'
        }
      },
      type: {
        required: true,
        serializedName: 'type',
        type: {
          name: 'String'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      nickname: {
        required: false,
        serializedName: 'nickname',
        type: {
          name: 'String'
        }
      },
      email: {
        required: true,
        serializedName: 'email',
        type: {
          name: 'String'
        }
      },
      redirectUrl: {
        required: false,
        serializedName: 'redirectUrl',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const BankAccountResponseModel = {
  required: false,
  serializedName: 'BankAccountResponseModel',
  type: {
    name: 'Composite',
    className: 'BankAccountResponseModel',
    modelProperties: {
      token: {
        required: false,
        serializedName: 'token',
        type: {
          name: 'String'
        }
      },
      bankAccountState: {
        required: false,
        serializedName: 'bankAccountState',
        type: {
          name: 'String'
        }
      },
      redirectUrl: {
        required: false,
        serializedName: 'redirectUrl',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const UpdateBankAccountModel = {
  required: false,
  serializedName: 'UpdateBankAccountModel',
  type: {
    name: 'Composite',
    className: 'UpdateBankAccountModel',
    modelProperties: {
      token: {
        required: false,
        serializedName: 'token',
        type: {
          name: 'String'
        }
      },
      nickname: {
        required: false,
        serializedName: 'nickname',
        type: {
          name: 'String'
        }
      },
      accountHolderName: {
        required: true,
        serializedName: 'accountHolderName',
        type: {
          name: 'String'
        }
      },
      accountHolderAddress: {
        required: true,
        serializedName: 'accountHolderAddress',
        type: {
          name: 'Composite',
          className: 'Address'
        }
      },
      email: {
        required: true,
        serializedName: 'email',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const Bin = {
  required: false,
  serializedName: 'Bin',
  type: {
    name: 'Composite',
    className: 'Bin',
    modelProperties: {
      bin: {
        required: false,
        serializedName: 'bin',
        type: {
          name: 'String'
        }
      },
      brand: {
        required: false,
        readOnly: true,
        serializedName: 'brand',
        type: {
          name: 'String'
        }
      },
      isDebitCard: {
        required: false,
        serializedName: 'isDebitCard',
        type: {
          name: 'Boolean'
        }
      },
      isCheckCard: {
        required: false,
        serializedName: 'isCheckCard',
        type: {
          name: 'Boolean'
        }
      },
      isGiftCard: {
        required: false,
        serializedName: 'isGiftCard',
        type: {
          name: 'Boolean'
        }
      },
      isCorporateCard: {
        required: false,
        serializedName: 'isCorporateCard',
        type: {
          name: 'Boolean'
        }
      },
      isFleetCard: {
        required: false,
        serializedName: 'isFleetCard',
        type: {
          name: 'Boolean'
        }
      },
      isPrepaidCard: {
        required: false,
        serializedName: 'isPrepaidCard',
        type: {
          name: 'Boolean'
        }
      }
    }
  }
};

export const CheckoutResponseModel = {
  required: false,
  serializedName: 'CheckoutResponseModel',
  type: {
    name: 'Composite',
    className: 'CheckoutResponseModel',
    modelProperties: {
      checkoutId: {
        required: false,
        serializedName: 'checkoutId',
        type: {
          name: 'Number'
        }
      },
      clientId: {
        required: false,
        serializedName: 'clientId',
        type: {
          name: 'String'
        }
      },
      redirectUrl: {
        required: false,
        serializedName: 'redirectUrl',
        type: {
          name: 'String'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      amount: {
        required: false,
        serializedName: 'amount',
        type: {
          name: 'Number'
        }
      },
      nameOnAccount: {
        required: false,
        serializedName: 'nameOnAccount',
        type: {
          name: 'String'
        }
      },
      expirationDate: {
        required: false,
        serializedName: 'expirationDate',
        type: {
          name: 'DateTime'
        }
      },
      enableBillingInformation: {
        required: false,
        serializedName: 'enableBillingInformation',
        type: {
          name: 'Boolean'
        }
      },
      billingAddress: {
        required: false,
        serializedName: 'billingAddress',
        type: {
          name: 'Composite',
          className: 'Address'
        }
      },
      email: {
        required: false,
        serializedName: 'email',
        type: {
          name: 'String'
        }
      },
      requireEmail: {
        required: false,
        serializedName: 'requireEmail',
        type: {
          name: 'Boolean'
        }
      },
      enableSaveOption: {
        required: false,
        serializedName: 'enableSaveOption',
        type: {
          name: 'Boolean'
        }
      }
    }
  }
};

export const CheckoutRequestModel = {
  required: false,
  serializedName: 'CheckoutRequestModel',
  type: {
    name: 'Composite',
    className: 'CheckoutRequestModel',
    modelProperties: {
      redirectUrl: {
        required: false,
        serializedName: 'redirectUrl',
        type: {
          name: 'String'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      amount: {
        required: false,
        serializedName: 'amount',
        type: {
          name: 'Number'
        }
      },
      nameOnAccount: {
        required: false,
        serializedName: 'nameOnAccount',
        type: {
          name: 'String'
        }
      },
      expirationDate: {
        required: false,
        serializedName: 'expirationDate',
        type: {
          name: 'DateTime'
        }
      },
      enableBillingInformation: {
        required: false,
        serializedName: 'enableBillingInformation',
        type: {
          name: 'Boolean'
        }
      },
      billingAddress: {
        required: false,
        serializedName: 'billingAddress',
        type: {
          name: 'Composite',
          className: 'Address'
        }
      },
      email: {
        required: false,
        serializedName: 'email',
        type: {
          name: 'String'
        }
      },
      requireEmail: {
        required: false,
        serializedName: 'requireEmail',
        type: {
          name: 'Boolean'
        }
      },
      enableSaveOption: {
        required: false,
        serializedName: 'enableSaveOption',
        type: {
          name: 'Boolean'
        }
      }
    }
  }
};

export const CreditCardModel = {
  required: false,
  serializedName: 'CreditCardModel',
  type: {
    name: 'Composite',
    className: 'CreditCardModel',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      token: {
        required: false,
        serializedName: 'token',
        type: {
          name: 'String'
        }
      },
      cardHolderName: {
        required: false,
        serializedName: 'cardHolderName',
        type: {
          name: 'String'
        }
      },
      cardNumber: {
        required: false,
        serializedName: 'cardNumber',
        type: {
          name: 'String'
        }
      },
      expirationMonth: {
        required: false,
        serializedName: 'expirationMonth',
        type: {
          name: 'Number'
        }
      },
      expirationYear: {
        required: false,
        serializedName: 'expirationYear',
        type: {
          name: 'Number'
        }
      },
      billingAddress: {
        required: false,
        serializedName: 'billingAddress',
        type: {
          name: 'Composite',
          className: 'Address'
        }
      },
      email: {
        required: false,
        serializedName: 'email',
        type: {
          name: 'String'
        }
      },
      cardState: {
        required: false,
        serializedName: 'cardState',
        type: {
          name: 'String'
        }
      },
      cardType: {
        required: false,
        serializedName: 'cardType',
        type: {
          name: 'String'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      createdTime: {
        required: false,
        serializedName: 'createdTime',
        type: {
          name: 'DateTime'
        }
      },
      modifiedTime: {
        required: false,
        serializedName: 'modifiedTime',
        type: {
          name: 'DateTime'
        }
      }
    }
  }
};

export const CreditCardRequestModel = {
  required: false,
  serializedName: 'CreditCardRequestModel',
  type: {
    name: 'Composite',
    className: 'CreditCardRequestModel',
    modelProperties: {
      cardNumber: {
        required: true,
        serializedName: 'cardNumber',
        type: {
          name: 'String'
        }
      },
      securityCode: {
        required: true,
        serializedName: 'securityCode',
        constraints: {
          Pattern: '\d{3,4}'
        },
        type: {
          name: 'String'
        }
      },
      expirationMonth: {
        required: true,
        serializedName: 'expirationMonth',
        constraints: {
          InclusiveMaximum: 12,
          InclusiveMinimum: 1
        },
        type: {
          name: 'Number'
        }
      },
      expirationYear: {
        required: true,
        serializedName: 'expirationYear',
        constraints: {
          InclusiveMaximum: 2038,
          InclusiveMinimum: 2018
        },
        type: {
          name: 'Number'
        }
      },
      cardHolderName: {
        required: true,
        serializedName: 'cardHolderName',
        type: {
          name: 'String'
        }
      },
      billingAddress: {
        required: true,
        serializedName: 'billingAddress',
        type: {
          name: 'Composite',
          className: 'Address'
        }
      },
      email: {
        required: true,
        serializedName: 'email',
        type: {
          name: 'String'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      redirectUrl: {
        required: false,
        serializedName: 'redirectUrl',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const CreditCardResponseModel = {
  required: false,
  serializedName: 'CreditCardResponseModel',
  type: {
    name: 'Composite',
    className: 'CreditCardResponseModel',
    modelProperties: {
      token: {
        required: false,
        serializedName: 'token',
        type: {
          name: 'String'
        }
      },
      cardState: {
        required: false,
        serializedName: 'cardState',
        type: {
          name: 'String'
        }
      },
      code: {
        required: false,
        serializedName: 'code',
        type: {
          name: 'String'
        }
      },
      message: {
        required: false,
        serializedName: 'message',
        type: {
          name: 'String'
        }
      },
      redirectUrl: {
        required: false,
        serializedName: 'redirectUrl',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const UpdateCreditCardModel = {
  required: false,
  serializedName: 'UpdateCreditCardModel',
  type: {
    name: 'Composite',
    className: 'UpdateCreditCardModel',
    modelProperties: {
      token: {
        required: true,
        serializedName: 'token',
        type: {
          name: 'String'
        }
      },
      expirationMonth: {
        required: true,
        serializedName: 'expirationMonth',
        constraints: {
          InclusiveMaximum: 12,
          InclusiveMinimum: 1
        },
        type: {
          name: 'Number'
        }
      },
      expirationYear: {
        required: true,
        serializedName: 'expirationYear',
        constraints: {
          InclusiveMaximum: 2038,
          InclusiveMinimum: 2018
        },
        type: {
          name: 'Number'
        }
      },
      cardHolderName: {
        required: true,
        serializedName: 'cardHolderName',
        type: {
          name: 'String'
        }
      },
      billingAddress: {
        required: true,
        serializedName: 'billingAddress',
        type: {
          name: 'Composite',
          className: 'Address'
        }
      },
      email: {
        required: true,
        serializedName: 'email',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const PaymentMethodModel = {
  required: false,
  serializedName: 'PaymentMethodModel',
  type: {
    name: 'Composite',
    className: 'PaymentMethodModel',
    modelProperties: {
      paymentToken: {
        required: true,
        serializedName: 'paymentToken',
        type: {
          name: 'String'
        }
      },
      type: {
        required: true,
        serializedName: 'type',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const PaymentResultModel = {
  required: false,
  serializedName: 'PaymentResultModel',
  type: {
    name: 'Composite',
    className: 'PaymentResultModel',
    modelProperties: {
      status: {
        required: false,
        serializedName: 'status',
        type: {
          name: 'String'
        }
      },
      code: {
        required: false,
        serializedName: 'code',
        type: {
          name: 'String'
        }
      },
      message: {
        required: false,
        serializedName: 'message',
        type: {
          name: 'String'
        }
      },
      providerAccountId: {
        required: false,
        serializedName: 'providerAccountId',
        type: {
          name: 'String'
        }
      },
      merchantTransactionId: {
        required: false,
        serializedName: 'merchantTransactionId',
        type: {
          name: 'String'
        }
      },
      merchantTransactionFee: {
        required: false,
        serializedName: 'merchantTransactionFee',
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const RefundResultModel = {
  required: false,
  serializedName: 'RefundResultModel',
  type: {
    name: 'Composite',
    className: 'RefundResultModel',
    modelProperties: {
      status: {
        required: false,
        serializedName: 'status',
        type: {
          name: 'String'
        }
      },
      code: {
        required: false,
        serializedName: 'code',
        type: {
          name: 'String'
        }
      },
      message: {
        required: false,
        serializedName: 'message',
        type: {
          name: 'String'
        }
      },
      merchantTransactionId: {
        required: false,
        serializedName: 'merchantTransactionId',
        type: {
          name: 'String'
        }
      },
      providerAccountId: {
        required: false,
        serializedName: 'providerAccountId',
        type: {
          name: 'String'
        }
      },
      amount: {
        required: false,
        serializedName: 'amount',
        type: {
          name: 'Number'
        }
      },
      reason: {
        required: false,
        serializedName: 'reason',
        type: {
          name: 'String'
        }
      },
      createdDate: {
        required: false,
        serializedName: 'createdDate',
        type: {
          name: 'DateTime'
        }
      }
    }
  }
};

export const PaymentModel = {
  required: false,
  serializedName: 'PaymentModel',
  type: {
    name: 'Composite',
    className: 'PaymentModel',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      accountId: {
        required: false,
        serializedName: 'accountId',
        type: {
          name: 'Number'
        }
      },
      paymentAmount: {
        required: false,
        serializedName: 'paymentAmount',
        type: {
          name: 'Number'
        }
      },
      description: {
        required: false,
        serializedName: 'description',
        type: {
          name: 'String'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      paymentMethod: {
        required: false,
        serializedName: 'paymentMethod',
        type: {
          name: 'Composite',
          className: 'PaymentMethodModel'
        }
      },
      result: {
        required: false,
        serializedName: 'result',
        type: {
          name: 'Composite',
          className: 'PaymentResultModel'
        }
      },
      refunds: {
        required: false,
        serializedName: 'refunds',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'RefundResultModelElementType',
              type: {
                name: 'Composite',
                className: 'RefundResultModel'
              }
          }
        }
      },
      createdDate: {
        required: false,
        serializedName: 'createdDate',
        type: {
          name: 'DateTime'
        }
      },
      modifiedDate: {
        required: false,
        serializedName: 'modifiedDate',
        type: {
          name: 'DateTime'
        }
      }
    }
  }
};

export const PaymentFilter = {
  required: false,
  serializedName: 'PaymentFilter',
  type: {
    name: 'Composite',
    className: 'PaymentFilter',
    modelProperties: {
      referenceId: {
        required: true,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      minDate: {
        required: false,
        serializedName: 'minDate',
        type: {
          name: 'DateTime'
        }
      },
      maxDate: {
        required: false,
        serializedName: 'maxDate',
        type: {
          name: 'DateTime'
        }
      }
    }
  }
};

export const PaymentRequestModel = {
  required: false,
  serializedName: 'PaymentRequestModel',
  type: {
    name: 'Composite',
    className: 'PaymentRequestModel',
    modelProperties: {
      paymentAmount: {
        required: false,
        serializedName: 'paymentAmount',
        type: {
          name: 'Number'
        }
      },
      description: {
        required: false,
        serializedName: 'description',
        type: {
          name: 'String'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      paymentMethod: {
        required: true,
        serializedName: 'paymentMethod',
        type: {
          name: 'Composite',
          className: 'PaymentMethodModel'
        }
      },
      callbackUrl: {
        required: false,
        serializedName: 'callbackUrl',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const RefundRequestModel = {
  required: false,
  serializedName: 'RefundRequestModel',
  type: {
    name: 'Composite',
    className: 'RefundRequestModel',
    modelProperties: {
      amount: {
        required: false,
        serializedName: 'amount',
        type: {
          name: 'Number'
        }
      },
      reason: {
        required: true,
        serializedName: 'reason',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const SubscriptionModel = {
  required: false,
  serializedName: 'SubscriptionModel',
  type: {
    name: 'Composite',
    className: 'SubscriptionModel',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      name: {
        required: false,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      description: {
        required: false,
        serializedName: 'description',
        type: {
          name: 'String'
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Dictionary',
          value: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      },
      runDay: {
        required: false,
        serializedName: 'runDay',
        type: {
          name: 'Number'
        }
      },
      state: {
        required: false,
        serializedName: 'state',
        type: {
          name: 'String'
        }
      },
      paymentType: {
        required: false,
        serializedName: 'paymentType',
        type: {
          name: 'String'
        }
      },
      paymentToken: {
        required: false,
        serializedName: 'paymentToken',
        type: {
          name: 'String'
        }
      },
      amountType: {
        required: false,
        serializedName: 'amountType',
        type: {
          name: 'String'
        }
      },
      amount: {
        required: false,
        serializedName: 'amount',
        type: {
          name: 'Number'
        }
      },
      amountWebServiceURL: {
        required: false,
        serializedName: 'amountWebServiceURL',
        type: {
          name: 'String'
        }
      },
      callbackWebServiceURL: {
        required: false,
        serializedName: 'callbackWebServiceURL',
        type: {
          name: 'String'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      lastProcessed: {
        required: false,
        serializedName: 'lastProcessed',
        type: {
          name: 'DateTime'
        }
      },
      endDate: {
        required: false,
        serializedName: 'endDate',
        type: {
          name: 'DateTime'
        }
      },
      createdTime: {
        required: false,
        serializedName: 'createdTime',
        type: {
          name: 'DateTime'
        }
      },
      modifiedTime: {
        required: false,
        serializedName: 'modifiedTime',
        type: {
          name: 'DateTime'
        }
      }
    }
  }
};

export const SubscriptionRequestModel = {
  required: false,
  serializedName: 'SubscriptionRequestModel',
  type: {
    name: 'Composite',
    className: 'SubscriptionRequestModel',
    modelProperties: {
      name: {
        required: true,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      description: {
        required: false,
        serializedName: 'description',
        type: {
          name: 'String'
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Dictionary',
          value: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      },
      runDay: {
        required: true,
        serializedName: 'runDay',
        constraints: {
          InclusiveMaximum: 31,
          InclusiveMinimum: 1
        },
        type: {
          name: 'Number'
        }
      },
      state: {
        required: true,
        serializedName: 'state',
        type: {
          name: 'String'
        }
      },
      paymentType: {
        required: true,
        serializedName: 'paymentType',
        type: {
          name: 'String'
        }
      },
      paymentToken: {
        required: true,
        serializedName: 'paymentToken',
        type: {
          name: 'String'
        }
      },
      amountType: {
        required: true,
        serializedName: 'amountType',
        type: {
          name: 'String'
        }
      },
      amount: {
        required: false,
        serializedName: 'amount',
        type: {
          name: 'Number'
        }
      },
      amountWebServiceURL: {
        required: false,
        serializedName: 'amountWebServiceURL',
        type: {
          name: 'String'
        }
      },
      callbackWebServiceURL: {
        required: false,
        serializedName: 'callbackWebServiceURL',
        type: {
          name: 'String'
        }
      },
      endDate: {
        required: false,
        serializedName: 'endDate',
        type: {
          name: 'DateTime'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const SubscriptionResponceModel = {
  required: false,
  serializedName: 'SubscriptionResponceModel',
  type: {
    name: 'Composite',
    className: 'SubscriptionResponceModel',
    modelProperties: {
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      },
      state: {
        required: false,
        serializedName: 'state',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const UpdateSubscriptionModel = {
  required: false,
  serializedName: 'UpdateSubscriptionModel',
  type: {
    name: 'Composite',
    className: 'UpdateSubscriptionModel',
    modelProperties: {
      id: {
        required: true,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      name: {
        required: true,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      description: {
        required: false,
        serializedName: 'description',
        type: {
          name: 'String'
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Dictionary',
          value: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      },
      runDay: {
        required: true,
        serializedName: 'runDay',
        constraints: {
          InclusiveMaximum: 31,
          InclusiveMinimum: 1
        },
        type: {
          name: 'Number'
        }
      },
      state: {
        required: true,
        serializedName: 'state',
        type: {
          name: 'String'
        }
      },
      paymentType: {
        required: true,
        serializedName: 'paymentType',
        type: {
          name: 'String'
        }
      },
      paymentToken: {
        required: true,
        serializedName: 'paymentToken',
        type: {
          name: 'String'
        }
      },
      amountType: {
        required: true,
        serializedName: 'amountType',
        type: {
          name: 'String'
        }
      },
      amount: {
        required: false,
        serializedName: 'amount',
        type: {
          name: 'Number'
        }
      },
      amountWebServiceURL: {
        required: false,
        serializedName: 'amountWebServiceURL',
        type: {
          name: 'String'
        }
      },
      callbackWebServiceURL: {
        required: false,
        serializedName: 'callbackWebServiceURL',
        type: {
          name: 'String'
        }
      },
      endDate: {
        required: false,
        serializedName: 'endDate',
        type: {
          name: 'DateTime'
        }
      },
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const WalletModel = {
  required: false,
  serializedName: 'WalletModel',
  type: {
    name: 'Composite',
    className: 'WalletModel',
    modelProperties: {
      id: {
        required: true,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      defaultToken: {
        required: false,
        serializedName: 'defaultToken',
        type: {
          name: 'String'
        }
      },
      creditCards: {
        required: false,
        serializedName: 'creditCards',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'CreditCardModelElementType',
              type: {
                name: 'Composite',
                className: 'CreditCardModel'
              }
          }
        }
      },
      bankAccounts: {
        required: false,
        serializedName: 'bankAccounts',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'BankAccountModelElementType',
              type: {
                name: 'Composite',
                className: 'BankAccountModel'
              }
          }
        }
      }
    }
  }
};

export const WalletRequestModel = {
  required: false,
  serializedName: 'WalletRequestModel',
  type: {
    name: 'Composite',
    className: 'WalletRequestModel',
    modelProperties: {
      referenceId: {
        required: false,
        serializedName: 'referenceId',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const WalletCreditCardRequestModel = {
  required: false,
  serializedName: 'WalletCreditCardRequestModel',
  type: {
    name: 'Composite',
    className: 'WalletCreditCardRequestModel',
    modelProperties: {
      paymentToken: {
        required: false,
        serializedName: 'paymentToken',
        type: {
          name: 'String'
        }
      },
      isDefault: {
        required: false,
        serializedName: 'isDefault',
        type: {
          name: 'Boolean'
        }
      }
    }
  }
};

export const WalletBankAccountRequestModel = {
  required: false,
  serializedName: 'WalletBankAccountRequestModel',
  type: {
    name: 'Composite',
    className: 'WalletBankAccountRequestModel',
    modelProperties: {
      paymentToken: {
        required: false,
        serializedName: 'paymentToken',
        type: {
          name: 'String'
        }
      },
      isDefault: {
        required: false,
        serializedName: 'isDefault',
        type: {
          name: 'Boolean'
        }
      }
    }
  }
};

export const SoftheonWalletAPIGetPaymentsByReferenceIdOptionalParams = {
  required: false,
  serializedName: 'GetPaymentsByReferenceIdOptions',
  type: {
    name: 'Composite',
    className: 'SoftheonWalletAPIGetPaymentsByReferenceIdOptionalParams',
    modelProperties: {
      minDate: {
        required: false,
        serializedName: 'minDate',
        type: {
          name: 'DateTime'
        }
      },
      maxDate: {
        required: false,
        serializedName: 'maxDate',
        type: {
          name: 'DateTime'
        }
      }
    }
  }
};
