/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


export const Address = {
  serializedName: "Address",
  type: {
    name: "Composite",
    className: "Address",
    modelProperties: {
      address1: {
        required: true,
        serializedName: "address1",
        type: {
          name: "String"
        }
      },
      address2: {
        serializedName: "address2",
        type: {
          name: "String"
        }
      },
      city: {
        required: true,
        serializedName: "city",
        type: {
          name: "String"
        }
      },
      state: {
        required: true,
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      zipCode: {
        required: true,
        serializedName: "zipCode",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BankAccountModel = {
  serializedName: "BankAccountModel",
  type: {
    name: "Composite",
    className: "BankAccountModel",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      },
      accountNumber: {
        serializedName: "accountNumber",
        constraints: {
          Pattern: /\d{4,17}$/
        },
        type: {
          name: "String"
        }
      },
      routingNumber: {
        required: true,
        serializedName: "routingNumber",
        constraints: {
          Pattern: /\d{9,9}$/
        },
        type: {
          name: "String"
        }
      },
      type: {
        required: true,
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      state: {
        required: true,
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      nickname: {
        serializedName: "nickname",
        type: {
          name: "String"
        }
      },
      accountHolderName: {
        required: true,
        serializedName: "accountHolderName",
        type: {
          name: "String"
        }
      },
      accountHolderAddress: {
        required: true,
        serializedName: "accountHolderAddress",
        type: {
          name: "Composite",
          className: "Address"
        }
      },
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      createdTime: {
        serializedName: "createdTime",
        type: {
          name: "DateTime"
        }
      },
      modifiedTime: {
        serializedName: "modifiedTime",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const UpdateBankAccountModel = {
  serializedName: "UpdateBankAccountModel",
  type: {
    name: "Composite",
    className: "UpdateBankAccountModel",
    modelProperties: {
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      },
      nickname: {
        serializedName: "nickname",
        type: {
          name: "String"
        }
      },
      accountHolderName: {
        required: true,
        serializedName: "accountHolderName",
        type: {
          name: "String"
        }
      },
      accountHolderAddress: {
        required: true,
        serializedName: "accountHolderAddress",
        type: {
          name: "Composite",
          className: "Address"
        }
      },
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BankAccountRequestModel = {
  serializedName: "BankAccountRequestModel",
  type: {
    name: "Composite",
    className: "BankAccountRequestModel",
    modelProperties: {
      accountNumber: {
        required: true,
        serializedName: "accountNumber",
        constraints: {
          Pattern: /\d{4,17}$/
        },
        type: {
          name: "String"
        }
      },
      routingNumber: {
        required: true,
        serializedName: "routingNumber",
        constraints: {
          Pattern: /\d{9,9}$/
        },
        type: {
          name: "String"
        }
      },
      accountHolderName: {
        required: true,
        serializedName: "accountHolderName",
        type: {
          name: "String"
        }
      },
      accountHolderAddress: {
        required: true,
        serializedName: "accountHolderAddress",
        type: {
          name: "Composite",
          className: "Address"
        }
      },
      type: {
        required: true,
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      nickname: {
        serializedName: "nickname",
        type: {
          name: "String"
        }
      },
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      redirectUrl: {
        serializedName: "redirectUrl",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BankAccountResponseModel = {
  serializedName: "BankAccountResponseModel",
  type: {
    name: "Composite",
    className: "BankAccountResponseModel",
    modelProperties: {
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      },
      bankAccountState: {
        serializedName: "bankAccountState",
        type: {
          name: "String"
        }
      },
      redirectUrl: {
        serializedName: "redirectUrl",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const BinRequestModel = {
  serializedName: "BinRequestModel",
  type: {
    name: "Composite",
    className: "BinRequestModel",
    modelProperties: {
      cardNumber: {
        required: true,
        serializedName: "cardNumber",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Bin = {
  serializedName: "Bin",
  type: {
    name: "Composite",
    className: "Bin",
    modelProperties: {
      bin: {
        serializedName: "bin",
        type: {
          name: "String"
        }
      },
      brand: {
        readOnly: true,
        serializedName: "brand",
        type: {
          name: "String"
        }
      },
      isDebitCard: {
        serializedName: "isDebitCard",
        type: {
          name: "Boolean"
        }
      },
      isCheckCard: {
        serializedName: "isCheckCard",
        type: {
          name: "Boolean"
        }
      },
      isGiftCard: {
        serializedName: "isGiftCard",
        type: {
          name: "Boolean"
        }
      },
      isCorporateCard: {
        serializedName: "isCorporateCard",
        type: {
          name: "Boolean"
        }
      },
      isFleetCard: {
        serializedName: "isFleetCard",
        type: {
          name: "Boolean"
        }
      },
      isPrepaidCard: {
        serializedName: "isPrepaidCard",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const CheckoutResponseModel = {
  serializedName: "CheckoutResponseModel",
  type: {
    name: "Composite",
    className: "CheckoutResponseModel",
    modelProperties: {
      checkoutId: {
        serializedName: "checkoutId",
        type: {
          name: "Number"
        }
      },
      clientId: {
        serializedName: "clientId",
        type: {
          name: "String"
        }
      },
      redirectUrl: {
        serializedName: "redirectUrl",
        type: {
          name: "String"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      nameOnAccount: {
        serializedName: "nameOnAccount",
        type: {
          name: "String"
        }
      },
      expirationDate: {
        serializedName: "expirationDate",
        type: {
          name: "DateTime"
        }
      },
      enableBillingInformation: {
        serializedName: "enableBillingInformation",
        type: {
          name: "Boolean"
        }
      },
      billingAddress: {
        serializedName: "billingAddress",
        type: {
          name: "Composite",
          className: "Address"
        }
      },
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      requireEmail: {
        serializedName: "requireEmail",
        type: {
          name: "Boolean"
        }
      },
      enableSaveOption: {
        serializedName: "enableSaveOption",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const CheckoutRequestModel = {
  serializedName: "CheckoutRequestModel",
  type: {
    name: "Composite",
    className: "CheckoutRequestModel",
    modelProperties: {
      redirectUrl: {
        serializedName: "redirectUrl",
        type: {
          name: "String"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      nameOnAccount: {
        serializedName: "nameOnAccount",
        type: {
          name: "String"
        }
      },
      expirationDate: {
        serializedName: "expirationDate",
        type: {
          name: "DateTime"
        }
      },
      enableBillingInformation: {
        serializedName: "enableBillingInformation",
        type: {
          name: "Boolean"
        }
      },
      billingAddress: {
        serializedName: "billingAddress",
        type: {
          name: "Composite",
          className: "Address"
        }
      },
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      requireEmail: {
        serializedName: "requireEmail",
        type: {
          name: "Boolean"
        }
      },
      enableSaveOption: {
        serializedName: "enableSaveOption",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const CreditCardModel = {
  serializedName: "CreditCardModel",
  type: {
    name: "Composite",
    className: "CreditCardModel",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      },
      cardHolderName: {
        serializedName: "cardHolderName",
        type: {
          name: "String"
        }
      },
      cardNumber: {
        serializedName: "cardNumber",
        type: {
          name: "String"
        }
      },
      expirationMonth: {
        serializedName: "expirationMonth",
        type: {
          name: "Number"
        }
      },
      expirationYear: {
        serializedName: "expirationYear",
        type: {
          name: "Number"
        }
      },
      billingAddress: {
        serializedName: "billingAddress",
        type: {
          name: "Composite",
          className: "Address"
        }
      },
      email: {
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      cardState: {
        serializedName: "cardState",
        type: {
          name: "String"
        }
      },
      cardType: {
        serializedName: "cardType",
        type: {
          name: "String"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      createdTime: {
        serializedName: "createdTime",
        type: {
          name: "DateTime"
        }
      },
      modifiedTime: {
        serializedName: "modifiedTime",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const UpdateCreditCardModel = {
  serializedName: "UpdateCreditCardModel",
  type: {
    name: "Composite",
    className: "UpdateCreditCardModel",
    modelProperties: {
      token: {
        required: true,
        serializedName: "token",
        type: {
          name: "String"
        }
      },
      expirationMonth: {
        required: true,
        serializedName: "expirationMonth",
        constraints: {
          InclusiveMaximum: 12,
          InclusiveMinimum: 1
        },
        type: {
          name: "Number"
        }
      },
      expirationYear: {
        required: true,
        serializedName: "expirationYear",
        constraints: {
          InclusiveMaximum: 2038,
          InclusiveMinimum: 2018
        },
        type: {
          name: "Number"
        }
      },
      cardHolderName: {
        required: true,
        serializedName: "cardHolderName",
        type: {
          name: "String"
        }
      },
      billingAddress: {
        required: true,
        serializedName: "billingAddress",
        type: {
          name: "Composite",
          className: "Address"
        }
      },
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CreditCardRequestModel = {
  serializedName: "CreditCardRequestModel",
  type: {
    name: "Composite",
    className: "CreditCardRequestModel",
    modelProperties: {
      cardNumber: {
        required: true,
        serializedName: "cardNumber",
        type: {
          name: "String"
        }
      },
      securityCode: {
        required: true,
        serializedName: "securityCode",
        constraints: {
          Pattern: /\d{3,4}/
        },
        type: {
          name: "String"
        }
      },
      expirationMonth: {
        required: true,
        serializedName: "expirationMonth",
        constraints: {
          InclusiveMaximum: 12,
          InclusiveMinimum: 1
        },
        type: {
          name: "Number"
        }
      },
      expirationYear: {
        required: true,
        serializedName: "expirationYear",
        constraints: {
          InclusiveMaximum: 2038,
          InclusiveMinimum: 2018
        },
        type: {
          name: "Number"
        }
      },
      cardHolderName: {
        required: true,
        serializedName: "cardHolderName",
        type: {
          name: "String"
        }
      },
      billingAddress: {
        required: true,
        serializedName: "billingAddress",
        type: {
          name: "Composite",
          className: "Address"
        }
      },
      email: {
        required: true,
        serializedName: "email",
        type: {
          name: "String"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      redirectUrl: {
        serializedName: "redirectUrl",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const CreditCardResponseModel = {
  serializedName: "CreditCardResponseModel",
  type: {
    name: "Composite",
    className: "CreditCardResponseModel",
    modelProperties: {
      token: {
        serializedName: "token",
        type: {
          name: "String"
        }
      },
      cardState: {
        serializedName: "cardState",
        type: {
          name: "String"
        }
      },
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        type: {
          name: "String"
        }
      },
      redirectUrl: {
        serializedName: "redirectUrl",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const PaymentMethodModel = {
  serializedName: "PaymentMethodModel",
  type: {
    name: "Composite",
    className: "PaymentMethodModel",
    modelProperties: {
      paymentToken: {
        required: true,
        serializedName: "paymentToken",
        type: {
          name: "String"
        }
      },
      type: {
        required: true,
        serializedName: "type",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const PaymentResultModel = {
  serializedName: "PaymentResultModel",
  type: {
    name: "Composite",
    className: "PaymentResultModel",
    modelProperties: {
      status: {
        serializedName: "status",
        type: {
          name: "String"
        }
      },
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        type: {
          name: "String"
        }
      },
      providerAccountId: {
        serializedName: "providerAccountId",
        type: {
          name: "String"
        }
      },
      merchantTransactionId: {
        serializedName: "merchantTransactionId",
        type: {
          name: "String"
        }
      },
      merchantTransactionFee: {
        serializedName: "merchantTransactionFee",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const RefundResultModel = {
  serializedName: "RefundResultModel",
  type: {
    name: "Composite",
    className: "RefundResultModel",
    modelProperties: {
      status: {
        serializedName: "status",
        type: {
          name: "String"
        }
      },
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        type: {
          name: "String"
        }
      },
      merchantTransactionId: {
        serializedName: "merchantTransactionId",
        type: {
          name: "String"
        }
      },
      providerAccountId: {
        serializedName: "providerAccountId",
        type: {
          name: "String"
        }
      },
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      reason: {
        serializedName: "reason",
        type: {
          name: "String"
        }
      },
      createdDate: {
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const PaymentModel = {
  serializedName: "PaymentModel",
  type: {
    name: "Composite",
    className: "PaymentModel",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      accountId: {
        serializedName: "accountId",
        type: {
          name: "Number"
        }
      },
      paymentAmount: {
        serializedName: "paymentAmount",
        type: {
          name: "Number"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      paymentMethod: {
        serializedName: "paymentMethod",
        type: {
          name: "Composite",
          className: "PaymentMethodModel"
        }
      },
      result: {
        serializedName: "result",
        type: {
          name: "Composite",
          className: "PaymentResultModel"
        }
      },
      refunds: {
        serializedName: "refunds",
        type: {
          name: "Sequence",
          element: {
            serializedName: "RefundResultModelElementType",
            type: {
              name: "Composite",
              className: "RefundResultModel"
            }
          }
        }
      },
      createdDate: {
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      },
      modifiedDate: {
        serializedName: "modifiedDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const BaseQuery = {
  serializedName: "BaseQuery",
  type: {
    name: "Composite",
    className: "BaseQuery",
    modelProperties: {
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      minDate: {
        serializedName: "minDate",
        type: {
          name: "DateTime"
        }
      },
      maxDate: {
        serializedName: "maxDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const PaymentRequestModel = {
  serializedName: "PaymentRequestModel",
  type: {
    name: "Composite",
    className: "PaymentRequestModel",
    modelProperties: {
      paymentAmount: {
        serializedName: "paymentAmount",
        type: {
          name: "Number"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      paymentMethod: {
        required: true,
        serializedName: "paymentMethod",
        type: {
          name: "Composite",
          className: "PaymentMethodModel"
        }
      },
      callbackUrl: {
        serializedName: "callbackUrl",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const RefundRequestModel = {
  serializedName: "RefundRequestModel",
  type: {
    name: "Composite",
    className: "RefundRequestModel",
    modelProperties: {
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      reason: {
        required: true,
        serializedName: "reason",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SubscriptionModel = {
  serializedName: "SubscriptionModel",
  type: {
    name: "Composite",
    className: "SubscriptionModel",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      properties: {
        serializedName: "properties",
        type: {
          name: "Dictionary",
          value: {
            serializedName: "stringElementType",
            type: {
              name: "String"
            }
          }
        }
      },
      runDay: {
        serializedName: "runDay",
        type: {
          name: "Number"
        }
      },
      state: {
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      paymentType: {
        serializedName: "paymentType",
        type: {
          name: "String"
        }
      },
      paymentToken: {
        serializedName: "paymentToken",
        type: {
          name: "String"
        }
      },
      amountType: {
        serializedName: "amountType",
        type: {
          name: "String"
        }
      },
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      amountWebServiceURL: {
        serializedName: "amountWebServiceURL",
        type: {
          name: "String"
        }
      },
      callbackWebServiceURL: {
        serializedName: "callbackWebServiceURL",
        type: {
          name: "String"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      lastProcessed: {
        serializedName: "lastProcessed",
        type: {
          name: "DateTime"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      },
      createdTime: {
        serializedName: "createdTime",
        type: {
          name: "DateTime"
        }
      },
      modifiedTime: {
        serializedName: "modifiedTime",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const UpdateSubscriptionModel = {
  serializedName: "UpdateSubscriptionModel",
  type: {
    name: "Composite",
    className: "UpdateSubscriptionModel",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      properties: {
        serializedName: "properties",
        type: {
          name: "Dictionary",
          value: {
            serializedName: "stringElementType",
            type: {
              name: "String"
            }
          }
        }
      },
      runDay: {
        required: true,
        serializedName: "runDay",
        constraints: {
          InclusiveMaximum: 31,
          InclusiveMinimum: 1
        },
        type: {
          name: "Number"
        }
      },
      state: {
        required: true,
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      paymentType: {
        required: true,
        serializedName: "paymentType",
        type: {
          name: "String"
        }
      },
      paymentToken: {
        required: true,
        serializedName: "paymentToken",
        type: {
          name: "String"
        }
      },
      amountType: {
        required: true,
        serializedName: "amountType",
        type: {
          name: "String"
        }
      },
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      amountWebServiceURL: {
        serializedName: "amountWebServiceURL",
        type: {
          name: "String"
        }
      },
      callbackWebServiceURL: {
        serializedName: "callbackWebServiceURL",
        type: {
          name: "String"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SubscriptionRequestModel = {
  serializedName: "SubscriptionRequestModel",
  type: {
    name: "Composite",
    className: "SubscriptionRequestModel",
    modelProperties: {
      name: {
        required: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      properties: {
        serializedName: "properties",
        type: {
          name: "Dictionary",
          value: {
            serializedName: "stringElementType",
            type: {
              name: "String"
            }
          }
        }
      },
      runDay: {
        required: true,
        serializedName: "runDay",
        constraints: {
          InclusiveMaximum: 31,
          InclusiveMinimum: 1
        },
        type: {
          name: "Number"
        }
      },
      state: {
        required: true,
        serializedName: "state",
        type: {
          name: "String"
        }
      },
      paymentType: {
        required: true,
        serializedName: "paymentType",
        type: {
          name: "String"
        }
      },
      paymentToken: {
        required: true,
        serializedName: "paymentToken",
        type: {
          name: "String"
        }
      },
      amountType: {
        required: true,
        serializedName: "amountType",
        type: {
          name: "String"
        }
      },
      amount: {
        serializedName: "amount",
        type: {
          name: "Number"
        }
      },
      amountWebServiceURL: {
        serializedName: "amountWebServiceURL",
        type: {
          name: "String"
        }
      },
      callbackWebServiceURL: {
        serializedName: "callbackWebServiceURL",
        type: {
          name: "String"
        }
      },
      endDate: {
        serializedName: "endDate",
        type: {
          name: "DateTime"
        }
      },
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const SubscriptionResponseModel = {
  serializedName: "SubscriptionResponseModel",
  type: {
    name: "Composite",
    className: "SubscriptionResponseModel",
    modelProperties: {
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      state: {
        serializedName: "state",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WalletModel = {
  serializedName: "WalletModel",
  type: {
    name: "Composite",
    className: "WalletModel",
    modelProperties: {
      id: {
        required: true,
        serializedName: "id",
        type: {
          name: "Number"
        }
      },
      defaultToken: {
        serializedName: "defaultToken",
        type: {
          name: "String"
        }
      },
      creditCards: {
        serializedName: "creditCards",
        type: {
          name: "Sequence",
          element: {
            serializedName: "CreditCardModelElementType",
            type: {
              name: "Composite",
              className: "CreditCardModel"
            }
          }
        }
      },
      bankAccounts: {
        serializedName: "bankAccounts",
        type: {
          name: "Sequence",
          element: {
            serializedName: "BankAccountModelElementType",
            type: {
              name: "Composite",
              className: "BankAccountModel"
            }
          }
        }
      }
    }
  }
};

export const WalletRequestModel = {
  serializedName: "WalletRequestModel",
  type: {
    name: "Composite",
    className: "WalletRequestModel",
    modelProperties: {
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WalletCreditCardRequestModel = {
  serializedName: "WalletCreditCardRequestModel",
  type: {
    name: "Composite",
    className: "WalletCreditCardRequestModel",
    modelProperties: {
      paymentToken: {
        serializedName: "paymentToken",
        type: {
          name: "String"
        }
      },
      isDefault: {
        serializedName: "isDefault",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const WalletBankAccountRequestModel = {
  serializedName: "WalletBankAccountRequestModel",
  type: {
    name: "Composite",
    className: "WalletBankAccountRequestModel",
    modelProperties: {
      paymentToken: {
        serializedName: "paymentToken",
        type: {
          name: "String"
        }
      },
      isDefault: {
        serializedName: "isDefault",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const SoftheonWalletAPIGetPaymentsByReferenceIdOptionalParams = {
  serializedName: "GetPaymentsByReferenceIdOptions",
  type: {
    name: "Composite",
    className: "SoftheonWalletAPIGetPaymentsByReferenceIdOptionalParams",
    modelProperties: {
      referenceId: {
        serializedName: "referenceId",
        type: {
          name: "String"
        }
      },
      minDate: {
        serializedName: "minDate",
        type: {
          name: "DateTime"
        }
      },
      maxDate: {
        serializedName: "maxDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};
