# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class BankAccountResponseModel(Model):
    """The response model that is returned to the client when a new bank account
    is added
    to the platform.

    :param token: The payment token for the bank account.
    :type token: str
    :param bank_account_state: The state that the bank acocunt is in. Possible
     values include: 'Unknown', 'New', 'Pending', 'Authorized', 'Disabled'
    :type bank_account_state: str or ~softheon.wallet.api.client.models.enum
    :param redirect_url: The url that the client will be redirected to after
     the bank account has been created.
    :type redirect_url: str
    """

    _attribute_map = {
        'token': {'key': 'token', 'type': 'str'},
        'bank_account_state': {'key': 'bankAccountState', 'type': 'str'},
        'redirect_url': {'key': 'redirectUrl', 'type': 'str'},
    }

    def __init__(self, token=None, bank_account_state=None, redirect_url=None):
        super(BankAccountResponseModel, self).__init__()
        self.token = token
        self.bank_account_state = bank_account_state
        self.redirect_url = redirect_url
