# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PaymentRequestModel(Model):
    """The request model sent by the client to add a new payment to the platform.

    :param payment_amount: The payment amount.
    :type payment_amount: float
    :param description: The description of what will be paid for.
    :type description: str
    :param reference_id: The client application provided reference ID for the
     payment.
    :type reference_id: str
    :param payment_method: The method of payment.
    :type payment_method:
     ~softheon.wallet.api.client.models.PaymentMethodModel
    :param callback_url: The callback URL where payment notifications will be
     sent.  Payment notifications are sent when the
     state of a payment changes.  Notifications will be sent as an HTTP POST to
     the URL provided and will
     contain a PaymentId and optional ReferenceId, if one was provided when the
     payment was created.
    :type callback_url: str
    """

    _validation = {
        'payment_method': {'required': True},
    }

    _attribute_map = {
        'payment_amount': {'key': 'paymentAmount', 'type': 'float'},
        'description': {'key': 'description', 'type': 'str'},
        'reference_id': {'key': 'referenceId', 'type': 'str'},
        'payment_method': {'key': 'paymentMethod', 'type': 'PaymentMethodModel'},
        'callback_url': {'key': 'callbackUrl', 'type': 'str'},
    }

    def __init__(self, payment_method, payment_amount=None, description=None, reference_id=None, callback_url=None):
        super(PaymentRequestModel, self).__init__()
        self.payment_amount = payment_amount
        self.description = description
        self.reference_id = reference_id
        self.payment_method = payment_method
        self.callback_url = callback_url
